name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - run: |
        ls
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Build extension
      run: msbuild nord-vs-theme\src\NordTheme.sln /p:Configuration=Release /t:Rebuild
      env: 
        DeployExtension: False
