name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Build extension
      run: msbuild nord-vs-theme\src\NordTheme.sln /t:Rebuild
      working-directory: $GITHUB_WORKSPACE
      env: 
        DeployExtension: False
